
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Create a new flow
 */
async createFlow(flow: Flow) : Promise<Result<Flow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_flow", { flow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all flows
 */
async getFlows() : Promise<Result<Flow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_flows") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a specific flow by ID
 */
async getFlow(id: string) : Promise<Result<Flow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_flow", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a flow
 */
async deleteFlow(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_flow", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a flow
 */
async updateFlow(id: string, flow: Flow) : Promise<Result<Flow, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_flow", { id, flow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute a flow
 */
async executeFlow(flowId: string, params: Partial<{ [key in string]: JsonValue }>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_flow", { flowId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add node to flow graph
 */
async addNode(flowId: string, node: Node) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_node", { flowId, node }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove node from flow graph
 */
async removeNode(flowId: string, nodeId: string) : Promise<Result<Node, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_node", { flowId, nodeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add connection to flow graph
 */
async addConnection(flowId: string, connection: Connection) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_connection", { flowId, connection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get execution order (topological sort)
 */
async getExecutionOrder(flowId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_execution_order", { flowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate flow graph
 */
async validateGraph(flowId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_graph", { flowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear cache command - moved to commands module
 */
async clearCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open cache directory command - moved to commands module
 */
async openCacheDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_cache_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * 缓存配置
 */
export type CacheConfig = { 
/**
 * HTTP响应缓存策略
 */
http_cache?: HttpCachePolicy; 
/**
 * 缓存存储方式
 */
storage?: CacheStorage }
/**
 * 缓存存储方式
 */
export type CacheStorage = 
/**
 * 内存缓存
 */
"memory" | 
/**
 * 文件缓存
 */
"file" | 
/**
 * 混合缓存（内存+文件）
 */
"hybrid"
/**
 * 并发控制配置
 */
export type ConcurrencyConfig = { 
/**
 * 最大并发数（None=无限制）
 */
max_concurrent?: bigint | null; 
/**
 * 请求间隔（毫秒）
 */
delay_ms?: bigint | null; 
/**
 * 随机延迟范围（毫秒）
 */
random_delay_ms?: [bigint, bigint] | null; 
/**
 * 重试策略
 */
retry?: RetryPolicy | null }
/**
 * 连接定义（节点间的数据流）
 */
export type Connection = { 
/**
 * 源节点ID
 */
from_node: string; 
/**
 * 源端口ID
 */
from_port: string; 
/**
 * 目标节点ID
 */
to_node: string; 
/**
 * 目标端口ID
 */
to_port: string }
/**
 * Cookie配置
 */
export type CookieConfig = { 
/**
 * 是否启用Cookie
 */
enabled?: boolean; 
/**
 * Cookie存储方式
 */
storage?: CookieStorage }
/**
 * Cookie存储方式
 */
export type CookieStorage = 
/**
 * 内存存储（会话级）
 */
"memory" | 
/**
 * 文件存储（持久化）
 */
"file" | 
/**
 * 无存储
 */
"none"
/**
 * 数据类型枚举
 */
export type DataType = 
/**
 * 字符串
 */
"String" | 
/**
 * 数字
 */
"Number" | 
/**
 * 布尔值
 */
"Boolean" | 
/**
 * 数组
 */
"Array" | 
/**
 * 对象
 */
"Object" | 
/**
 * 二进制数据
 */
"Binary" | 
/**
 * 任意类型
 */
"Any"
/**
 * 单个流程定义
 */
export type Flow = 
/**
 * 流程配置
 */
({ 
/**
 * 流程类型
 */
flow_type?: FlowType; 
/**
 * 是否启用
 */
enabled?: boolean; 
/**
 * 流程描述
 */
description?: string | null; 
/**
 * 流程级HTTP配置（覆盖全局配置）
 */
http?: HttpConfig | null; 
/**
 * 流程级并发控制配置（覆盖全局配置）
 */
concurrency?: ConcurrencyConfig | null }) & { 
/**
 * 节点图
 */
graph: NodeGraph }
/**
 * 流程类型枚举
 */
export type FlowType = 
/**
 * 登录流程
 */
"login" | 
/**
 * 发现页流程
 */
"discovery" | 
/**
 * 搜索流程
 */
"search" | 
/**
 * 详情页流程
 */
"detail" | 
/**
 * 内容页流程
 */
"content"
/**
 * 全局配置
 */
export type GraphConfig = { 
/**
 * 媒体类型
 */
media_type?: MediaType; 
/**
 * 元数据
 */
meta?: Meta; 
/**
 * 全局HTTP配置
 */
http?: HttpConfig | null; 
/**
 * 缓存配置
 */
cache?: CacheConfig | null; 
/**
 * 并发控制配置
 */
concurrency?: ConcurrencyConfig | null }
/**
 * HTTP缓存策略
 */
export type HttpCachePolicy = 
/**
 * 不缓存
 */
"none" | 
/**
 * 遵循HTTP头（Cache-Control等）
 */
"respect_headers" | 
/**
 * 强制缓存所有响应
 */
"force" | 
/**
 * 智能缓存（默认，根据响应类型判断）
 */
"smart"
/**
 * HTTP请求配置
 */
export type HttpConfig = { 
/**
 * 默认请求头
 */
headers?: Partial<{ [key in string]: string }>; 
/**
 * 默认超时（毫秒）
 */
timeout?: bigint | null; 
/**
 * 默认重试次数
 */
retry?: bigint; 
/**
 * 默认User-Agent
 */
user_agent?: string | null; 
/**
 * 代理配置
 */
proxy?: ProxyConfig | null; 
/**
 * Cookie配置
 */
cookie?: CookieConfig | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * 媒体类型枚举
 */
export type MediaType = 
/**
 * 视频
 */
"video" | 
/**
 * 音乐/音频
 */
"music" | 
/**
 * 小说/书籍
 */
"novel" | 
/**
 * 漫画
 */
"comic" | 
/**
 * 图片
 */
"image" | 
/**
 * 通用/其他
 */
"general"
/**
 * 元数据
 */
export type Meta = 
/**
 * 其他自定义字段
 */
(Partial<{ [key in string]: null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }> }>) & { 
/**
 * 规则名称
 */
name?: string | null; 
/**
 * 规则描述
 */
description?: string | null; 
/**
 * 版本
 */
version?: string | null; 
/**
 * 作者
 */
author?: string | null; 
/**
 * 网站URL
 */
website?: string | null; 
/**
 * 图标URL
 */
icon?: string | null; 
/**
 * 自定义标签
 */
tags?: string[] }
/**
 * 节点定义
 */
export type Node = { 
/**
 * 节点唯一ID
 */
id: string; 
/**
 * 节点类型标识符
 */
node_type: string; 
/**
 * 节点配置（JSON格式，根据节点类型验证）
 */
config: JsonValue; 
/**
 * 输入端口定义
 */
inputs?: Port[]; 
/**
 * 输出端口定义
 */
outputs?: Port[]; 
/**
 * UI位置（仅前端使用，不影响执行）
 */
position?: Position | null; 
/**
 * 是否禁用（用于调试）
 */
disabled?: boolean }
/**
 * 节点图（核心数据结构）
 */
export type NodeGraph = { 
/**
 * 所有节点（使用HashMap以ID索引）
 */
nodes?: Partial<{ [key in string]: Node }>; 
/**
 * 所有连接
 */
connections?: Connection[]; 
/**
 * 全局配置
 */
config?: GraphConfig }
/**
 * 端口定义
 */
export type Port = { 
/**
 * 端口ID
 */
id: string; 
/**
 * 数据类型
 */
data_type: DataType; 
/**
 * 是否可选
 */
optional?: boolean; 
/**
 * 显示名称（用于UI）
 */
display_name?: string | null }
/**
 * UI位置（仅前端使用，不影响执行）
 */
export type Position = { 
/**
 * X坐标
 */
x: bigint; 
/**
 * Y坐标
 */
y: bigint }
/**
 * 代理配置
 */
export type ProxyConfig = { 
/**
 * 代理URL
 */
url: string; 
/**
 * 代理认证用户名
 */
username?: string | null; 
/**
 * 代理认证密码
 */
password?: string | null }
/**
 * 重试策略
 */
export type RetryPolicy = { 
/**
 * 最大重试次数
 */
max_retries?: bigint; 
/**
 * 重试延迟（毫秒）
 */
delay_ms?: bigint; 
/**
 * 指数退避
 */
exponential_backoff?: boolean; 
/**
 * 哪些状态码需要重试
 */
retry_on_status?: number[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
